networks:
  cep_rede:
    driver: bridge

volumes:
  cep_cache:

services:
  cep_redis:
    image: redis:alpine
    container_name: cep_redis
    restart: unless-stopped
    networks:
      - cep_rede
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cep_cache:/data
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
